[workspace]
# update dependencies with `cargo update`
dependencies_update = true
# create tags for the releases
git_tag_enable = true
# disable GitHub releases
git_release_enable = false
# labels for the release PR
pr_labels = ["release"]
# disallow updating repositories with uncommitted changes
allow_dirty = false
# disallow packaging with uncommitted changes
publish_allow_dirty = false
# disable running `cargo-semver-checks`
semver_check = false
# disable changelog/publish by default for all crates
changelog_update = false
publish = false

[[package]]
name = "flowrs-airflow"
publish = true
changelog_update = true

[[package]]
name = "flowrs-config"
publish = true
changelog_update = false

[[package]]
name = "flowrs-tui"
publish = true
changelog_update = true
