Set Shell zsh
Set Width 1600
Set Height 900
Sleep 1.5s
Sleep 500ms
Type "cargo run"
Enter
Sleep 5s
Type "j"
Sleep 500ms
Type "jjj"
Sleep 500ms
Type "/bash"
Sleep 500ms
Enter
Sleep 1.5s
Enter
Sleep 1.5s
Type "jjjj"
Sleep 1.5s
Type "c"
Sleep 500ms
Type "h"
Sleep 500ms
Enter
Sleep 2.5s
Type "j"
Sleep 500ms
Type "jjj"
Enter
Sleep 1s
Type "jjj"
Sleep 1s
Enter
Sleep 4s
Escape
Sleep 1s
Escape
Sleep 1s
Escape
Sleep 1s
Escape
Sleep 1.5s
Type "q"
Sleep 1.5s

