Set Shell zsh
Set Framerate 24
Set Width 1600
Set Height 1200
Require flowrs

Sleep 1s
Type "flowrs"
Sleep 1s
Enter
Sleep 3s
Type "jjjj"
Sleep 0.5s
Type "/bash"
Sleep 0.5s
Enter
Sleep 1s
Enter
Sleep 1s
Type "jjjj"
Sleep 1s
Type "c"
Sleep 0.5s
Type "h"
Sleep 1s
Enter
Sleep 2s
Type "jjjj"
Enter
Sleep 1s
Type "jjjj"
Sleep 1s
Enter
Sleep 3s
Escape
Sleep 1s
Escape
Sleep 1s
Escape
Sleep 1s
Escape
Sleep 1s
Type "q"
Sleep 1s

